sehlen-bsi/botan-docs

- cryptodoc/src/08_signatures.rst
- cryptodoc/src/90_bibliographie.rst
Documentation update for https://github.com/randombit/botan/pull/3393.
> Add hash truncation in ECKCDSA

- cryptodoc/src/01_hash.rst
- cryptodoc/src/90_bibliographie.rst
I tried to described the implementation in a level of detail similar to the other hash functions.
After merging #70 I will add `blake2` to the list of newly reviewed modules.
> Documentation: BLAKE2b

- cryptodoc/src/01_hash.rst
As with #72, we use #70 to insert SHAKE into the list of newly reviewed modules.
> Documentation: SHAKE

- tools/genaudit/genaudit/templates/topic.rst
It ain't much, but it's honest work.
> Chore: Make audit-chapters start on new pages

- docs/cryptodoc/src/00_01_changelog.rst
- docs/cryptodoc/src/07_rng.rst
> Adapt `BigInt::random_integer()`

- docs/audit_report/changes/topics/documentation.yml
- docs/audit_report/changes/topics/release.yml
> Audit: Documentation and Release Info

- docs/audit_report/changes/topics/extensions.yml
- docs/audit_report/changes/topics/fixes.yml
- docs/audit_report/changes/topics/python.yml
- docs/audit_report/changes/topics/xof.yml
I decided to create a new topic "Misc Extensions" and dissolve the single-patch topics "Python" and "XOF" into it.
> Audit: Fixes and Extensions

- README.md
Adds a status badge for the auto-updater. In the hope that it will help us notice failures in the automation.
> Doc: Auto-Update badge

- .github/scripts/ci_build.py
- .github/workflows/release.yml
... for easier (and much faster) handling of the GitHub Actions artefacts.
> CI: Package the HTML documentation into ZIP files

- README.md
- internal/release_checklist.md
As suggested in https://github.com/sehlen-bsi/botan-docs/pull/150#discussion_r1368602031.
> Add a Release Checklist Document

- .github/actions/setup-build-agent/setup_gh_actions.sh
Fix ported from https://github.com/randombit/botan/pull/3783.
> Add hack to work around GH Actions bug breaking the Clang build

- docs/architecture/poetry.lock
- docs/audit_method/poetry.lock
- docs/audit_report/poetry.lock
- docs/cryptodoc/poetry.lock
- docs/testreport/poetry.lock
- docs/testspec/poetry.lock
- tools/auditupdate/poetry.lock
- tools/auditutils/poetry.lock
- tools/genaudit/poetry.lock
- tools/sourceref/poetry.lock
Simply called `poetry update` in every folder that includes a `pyproject.toml` file. Hopefully that will fix the [dependabot warnings](https://github.com/sehlen-bsi/botan-docs/security/dependabot). We probably want to automate this at some point.
> Chore: Update Dependencies

- docs/audit_report/changes/topics/ci.yml
- docs/audit_report/changes/topics/documentation.yml
- docs/audit_report/changes/topics/release.yml
Once this and the other currently open Audit-PRs are merged, #167 should turn green and would be ready for merge.
Then, we should keep incoming patches up-to-date as they come in from the Auto-update Bot.
> Audit: Remaining bits

- .github/actions/setup-build-agent/setup_gh_actions.sh
See also: https://github.com/randombit/botan/pull/3833
> Update GHA workaround

- docs/architecture/src/conf.py
- docs/audit_method/src/conf.py
- docs/audit_report/src/conf.py
- docs/cryptodoc/src/conf.py
- docs/testreport/src/conf.py
- docs/testspec/src/conf.py
... the Sphinx default is US Letter.
> Use DIN A4 paper for the LaTeX rendering

- docs/testspec/src/12_pubkey_kem.rst
It contains what it says on the box...
> FrodoKEM: Test Specification

- docs/audit_report/src/06_bibliography.rst
- docs/audit_report/src/side_channels/01_00_results.rst
- docs/audit_report/src/side_channels/01_02_frodokem.rst
This is the FrodoKEM SCA report.
~~This branch sits on top of #153~~ (see: https://github.com/sehlen-bsi/botan-docs/pull/175#issuecomment-1880657495)
> FrodoKEM: Side Channel Analysis

- .github/actions/setup-build-agent/setup_gh_actions.sh
- .github/scripts/ci_build.py
Applying changes from https://github.com/randombit/botan/commit/ac89dbc3c3cce8f4608b55ff4091658aa05b3116 and https://github.com/randombit/botan/pull/3833/commits/c54c182dbd0e89a594f1439be41235872cde9034.
> FIX: CI build on macOS 13

- docs/audit_report/src/02_security_issues.rst
- docs/cryptodoc/src/05_08_kyber.rst
- docs/cryptodoc/src/90_bibliographie.rst
This adds an explanation for the improved countermeasure we introduced in https://github.com/randombit/botan/pull/3898. Note that the countermeasure is not yet merged.
> Kyberslash countermeasure explanation

- docs/cryptodoc/src/05_08_kyber.rst
Update for the simplified version introduced with https://github.com/randombit/botan/pull/3959.
> Kyberslash Countermeasure Update

- docs/cryptodoc/src/05_06_spx.rst
- docs/cryptodoc/src/05_09_frodokem.rst
Addresses https://github.com/sehlen-bsi/botan-docs/pull/186#discussion_r1587755285 in the existing algorithms
> Add explicit mode/parameter inputs

- docs/audit_report/src/06_bibliography.rst
- docs/audit_report/src/side_channels/01_00_results.rst
- docs/audit_report/src/side_channels/01_01_lms.rst
... as delivered by the AISEC collegues.
> HSS/LMS: Side Channel Analysis

- .github/actions/setup-build-agent/setup_gh_actions.sh
- .github/scripts/ci_build.py
- .github/workflows/ci.yml
- docs/audit_report/changes/topics/uncategorized.yml
- docs/cryptodoc/src/10_kdf.rst
A few minor fixes to repair CI on `main`.
> FIX: CI build on main branch

- docs/audit_report/changes/topics/tpm2.yml
> Audit of Botan 3.6.0: TPM2

- config/botan.env
- docs/audit_report/changes/topics/chore.yml
- docs/audit_report/changes/topics/fixes.yml
- docs/audit_report/changes/topics/pcurves.yml
- docs/audit_report/changes/topics/pqc.yml
- docs/audit_report/changes/topics/release.yml
- docs/audit_report/changes/topics/tls.yml
- tools/auditupdate/README.md
- tools/auditupdate/auditupdate/cli.py
- tools/genaudit/genaudit/repo.py
... this also contains a patch to the autoupdate tool to simplify preparing such last-minute hotfix updates.
> Audit: Botan 3.6.1 patches + Some missing annotations

- docs/audit_report/src/06_bibliography.rst
- docs/audit_report/src/side_channels/02_00_literature.rst
- docs/audit_report/src/side_channels/index.rst
Created by @taudor. This PR is for review purposes ;)
> SCA Literature Overview

- docs/audit_method/src/03_sidechannel_analysis.rst
- docs/testspec/src/90_valgrind_sca.rst
- docs/testspec/src/index.rst
> Testspec: Valgrind CT::poison() overview

- docs/audit_report/changes/topics/build.yml
> Audit: Build System Changes

- docs/audit_report/changes/topics/ci.yml
- docs/audit_report/changes/topics/fixes.yml
- docs/audit_report/changes/topics/tests.yml
This might merge-conflict with #273 because I moved a few patches in there.
> Audit: Test and Continuous Integration Updates

- docs/audit_report/changes/topics/pcurve.yml
- docs/audit_report/src/06_bibliography.rst
Optimizations in this section don't actually apply to ECC only. Probably we should just merge this with the "generic" optimization section.
> Audit: ECC optimizations

- docs/audit_report/changes/topics/optimizations.yml
- docs/cryptodoc/src/05_04_rsa.rst
- docs/cryptodoc/src/90_bibliographie.rst
- tools/auditinfo/auditinfo/document.py
I also updated the cryptodoc to reflect the changes discussed [here](https://github.com/randombit/botan/pull/4558/files#r1982936758).
> 3.7.1 Audit: Optimizations

- docs/audit_report/scripts/audited_modules_list.py
... this is useful to sanity-check if all relevant modules were listed.
> Allow printing 'skipped' modules in the audited_modules_list.py helper

- docs/architecture/src/00_preface.rst
- docs/audit_method/src/00_00_preface.rst
- docs/audit_report/src/00_00_preface.rst
- docs/cryptodoc/src/00_00_preface.rst
- docs/testreport/src/00_00_preface.rst
- docs/testspec/src/00_00_preface.rst
As discussed in #289, let's polish the preface a bit:
The first part of the preface is always the same in each document. I rewrote it in just one document as a suggestion. Let's iterate and copy the final result in the end.
> Doc: update preface
