sehlen-bsi/botan-docs

audit_method/src/01_change_tracking.rst, audit_method/src/06_summary.rst, audit_method/src/90_references.rst
That's the process document description to the suggested audit process change we discussed in the Jour Fixe on Feb 22nd 2023. Along with it comes a more detailed write-up of why SHA-1 as used in Git is still considered trustworthy, despite [the "SHAttered" attack](https://shattered.io/) by Stevens et al.
=> Describe the planned Audit Process based on Pull Requests and Master-Commits

auxiliary_documents/hybrid_tls_approaches.rst
This gives an overview of the existing proposals for a hybrid key exchange mechanism in TLS 1.3. It aims to be a deliverable for AP 5.1.
Currently, there is no CI job to transform this document into a PDF. Do we even need that?
Most notably, this contains references to:
* Douglas Stebila, Scott Fluhrer, Shay Gueron
"Hybrid key exchange in TLS 1.3", Internet Engineering Task Force, February 2023
https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/06/
* John M. Schanck, Douglas Stebila
"A Transport Layer Security (TLS) Extension For Establishing An Additional Shared Secret", Internet Engineering Task Force, April 2017
https://datatracker.ietf.org/doc/draft-schanck-tls-additional-keyshare/00/
* William Whyte, Zhenfei Zhang, Scott Fluhrer, Oscar Garcia-Morchon
"Quantum-Safe Hybrid …
=> Overview of the most-notable hybrid TLS approaches

audit_report/3.1.0/changes/config.yml, audit_report/3.1.0/changes/topics/auxiliary_scripts.yml, audit_report/3.1.0/changes/topics/build_system.yml, audit_report/3.1.0/changes/topics/ci.yml, audit_report/3.1.0/changes/topics/clang_format.yml, audit_report/3.1.0/changes/topics/code_chores.yml, audit_report/3.1.0/changes/topics/documentation.yml, audit_report/3.1.0/changes/topics/fixes.yml, audit_report/3.1.0/changes/topics/release.yml, audit_report/3.1.0/changes/topics/sphincsplus.yml, audit_report/3.1.0/changes/topics/test_framework.yml, audit_report/3.1.0/changes/topics/tls.yml
The document now covers all patches applied to the code base between `3.0.0-alpha1` and `3.1.0`.
For the record:
* 184 plain commits to master
* 434 merged pull requests
* 23 individual contributors
* 2032 files changed
* 194075 lines inserted
* 114684 lines deleted
Note that the diff stat is highly skewed by the introduction of clang-format.
=> Audit: Update patch coverage to Botan 3.1.0

.github/workflows/ci.yml, audit_generator/audit.py, audit_generator/genaudit/cache.py, audit_generator/genaudit/repo.py
The rate limit seems to be too tight, resulting in failed CI runs.
Closes #74
=> Log GitHub API Rate Limit and Cache Hit Rate

.github/scripts/query_rate_limit.sh, .github/workflows/ci.yml, audit_generator/audit.py
That's a second attempt (after #76) to work around the tight rate limit on the GitHub API. The idea: if the build job fails due to the rate limit exceeding, we store the (partial) disk cache of the generator script. Later runs of the build pipeline will be able to pick this up and (hopefully) complete the job from where the previous job had failed.
Closes #74
=> FIX: Store cache if building fails due to rate limit

audit_report/3.1.0/changes/topics/fixes.yml, audit_report/3.1.0/changes/topics/sphincsplus.yml, audit_report/3.1.0/changes/topics/tls.yml
Note that the missing entry in fixes.yml is progressed in #63.
=> Final 3.1.0 Audit: TLS, SPHINCS+, and Fixes

cryptodoc/src/09_rng.rst
Mostly to reflect the internal refactorings applied in: https://github.com/randombit/botan/pull/3195.
=> Cryptodoc: Update RNG info

testspec/src/14_pubkey_sig.rst, testspec/src/conf.py
Currently CI is failing with broken links because the upstream SPHINCS+ implementation is not yet merged.
=> Testspec: SPHINCS+

cryptodoc/src/06_pubkey_key_generation.rst, cryptodoc/src/08_signatures.rst, cryptodoc/src/90_bibliographie.rst, cryptodoc/src/conf.py
Since the [PR for SPHINCS+](https://github.com/randombit/botan/pull/3549) for Botan is not merged yet, the CI pipeline currently fails; the source-links cannot be found. However, we expect that the PR is merged soon next week after some minor adjustments were made.
=> Add SPHINCS+ Documentation

architecture/src/01_architecture.rst, architecture/src/conf.py
Minor typos, new directories in `src` and some adaptions to the PDF handbook section numbers.
=> Architecture: Updates for Botan 3.1.1

audit_report/3.1.0/src/07_bibliography.rst
When building the audit report with `make html` it complained that:
```
/home/meusel/Projects/BSI/botan-cryptodoc/docs/audit_report/src/index.rst:5: WARNING: toctree contains reference to document '07_bibliography' that doesn't have a title: no link will be generated
```
=> FIX: Headline is needed in each chapter when building HTML

.github/actions/setup-environment/action.yml, .github/environment/botan.env, .github/scripts/read_environment.py, .github/workflows/ci.yml, .github/workflows/release.yml
This stashes the base information about the Botan repo, the source code version and git reference into a central config file. A small custom action reads this config file and puts to contained info into environment variables for later consumption by the CI jobs.
=> Pull the Botan target info from a central config file

.github/workflows/ci.yml, codebase_exports/source_archive/generate.py
The concrete version to be zipped is stated in the `ci.yml`.
=> Generate a botan source tarball

.github/actions/setup-environment/action.yml
There might be easier ways to do that in powershell than [the one I found here](https://www.jamescroft.co.uk/setting-github-actions-environment-variables-in-powershell/). For instance, we could pass the `$GITHUB_ENV` file path straight to the `read_environment.py` and implement the file append/write in Python. But frankly: 😴.
=> FIX: Environment Configuration on Windows

.github/workflows/ci.yml
This runs the main build pipeline every 6-ish days to save the main branch's build cache from eviction when no-one works on this repository. Note that after about 60 days of repository inactivity GitHub will also suspend scheduled workflows. But that's a more realistic time window for consecutive edits of the documentation.
Admittedly, that's an evil hack. But I didn't find a way to manipulate the cache eviction policy.
=> Hack: Keep GitHub Actions caches warm

docs/architecture/src/01_architecture.rst, docs/architecture/src/conf.py, docs/audit_method/src/00_00_preface.rst, docs/audit_method/src/conf.py, docs/audit_report/src/00_00_preface.rst, docs/audit_report/src/00_09_introduction.rst, docs/audit_report/src/05_summary.rst, docs/audit_report/src/conf.py, docs/cryptodoc/src/00_00_preface.rst, docs/cryptodoc/src/conf.py, docs/testspec/src/00_00_preface.rst, docs/testspec/src/conf.py, tools/auditinfo/auditinfo/__init__.py, tools/auditinfo/auditinfo/base.py, tools/auditinfo/auditinfo/document.py
This adds a few global substitutions that are accessible in the reStructuredText sections of the documentation. Additionally, individual documents may define custom substitutions in their `conf.py`.
To use those in rST, simply type them inside pipe symbols as seen below. Note however, that substitutions will work in normal floating text only. Not inside code blocks!
```rst
This document was generated based on |document_gitsha_short| and targets |botan_version|.
```
Currently available substitutions:
| Substitution variable      | The generated value                                                                                                      |
| -------------------------- | -------------------------------------------------------------------------------------------------------------- …
=> Chore: Global Substitutions in rST

.github/workflows/ci.yml, docs/architecture/src/conf.py, docs/audit_method/src/conf.py, docs/audit_report/src/conf.py, docs/cryptodoc/src/conf.py, docs/testspec/src/conf.py
File names are now: `{docname}-botan-{botan_target_version}.pdf`. Where `docname` is "cryptodoc", "audit_report", etc. and `botan_target_version` is the final version of the current audit iteration.
=> Chore: More Specific Document File Names

docs/audit_report/changes/topics/kuznyechik.yml, docs/audit_report/src/06_bibliography.rst
For the record: Kuznyechik is explicitly prohibited in the BSI build policy and won't be compiled into the library when configured with that policy.
It is a National Standard of the Russian Federation and has [a questionable mathematical structure](https://eprint.iacr.org/2016/071) in its supposedly random S-boxes.
=> Audit: Kuznyechik

.github/workflows/auto-update.yml, tools/auditupdate/README.md, tools/auditupdate/auditupdate/cli.py, tools/auditupdate/poetry.lock, tools/auditupdate/pyproject.toml
* https://github.com/sehlen-bsi/botan-docs/pull/134
This registers an auto-update job that runs every night and checks the upstream Botan repository for new patches. As long as the current audit target is not pinned to a specific Botan version (i.e. `$BOTAN_REF` points to a commit SHA rather than a tag), this will automatically try to update the document with new patches.
If new patches are found, a pull request is opened, that contains references to those patches in the "uncategorized" topic. A human auditor can then manually categorize them and update the pull request with their Audit result.
Note that the auto-updater recognizes when an auto-update pull request is currently open and amend it as necessary.
=> CI: Auto-update Audit Document based on upstream patches

docs/cryptodoc/src/01_hash.rst
This change should fix the source-ref CI by considering https://github.com/randombit/botan/pull/3705 in the cryptodoc.
=> Cryptodoc Fix: MDx_HashFunction to MerkleDamgard_Hash

.github/workflows/auto-update.yml
This is a follow up of #145. The Auto-Updater needs to have the GitHub web-flow GPG key registered in its environment as well. It failed tonight. 😢
=> FIX: Auto-Update needs the GitHub GPG key

docs/audit_report/src/00_09_introduction.rst
* `certstor_system_macos`
* `certstor_system_windows`
* `certstor_sqlite3`
* `sha1_armv8`
* `sha1_sse2`
* `sha1_x86`
=> FIX: add some missing modules

config/botan.env, tools/auditinfo/auditinfo/botan.py, tools/genaudit/genaudit/audit.py
This allows building documents based on a patch-set that is not hosted on the Botan upstream repository. Use this, when you need to reference unmerged patches and adaptions. The GitHub API requests are directed towards BOTAN_UPSTREAM_REPO.
=> Introduce BOTAN_UPSTREAM_REPO config

docs/audit_report/changes/topics/chores.yml, docs/audit_report/changes/topics/chores_sensitive.yml
I split the "chores" into two topics to distinguish between chores that are relevant to security and those that are not. In 3.3.0 we refactored quite a bit of internal legacy code to use modern C++ helpers. Especially when handling raw byte buffers.
=> Audit: Code Chores

docs/audit_report/changes/topics/chores_sensitive.yml
References between topics are possible by simply specifying the topic's YAML file name (without file extension). But I didn't recall that one has to add the `changes` parent directory.
Admittedly, CI should catch things like that! Looking into it tmrw.
=> FIX: document-internal reference

docs/architecture/Makefile, docs/audit_method/Makefile, docs/audit_report/Makefile, docs/cryptodoc/Makefile, docs/testreport/Makefile, docs/testspec/Makefile
`-W` is "treat sphinx warnings as errors". For instance, a reference that cannot be resolved is a warning and won't fail the build, otherwise. Locally, the PDF generator produces so much terminal-barf that warnings are often overlooked, despite being rendered in a different color.
`--keep-going` doesn't immediately stop on the first error. That is useful in CI, because it shows all the broken things to be fixed. Hopefully, that makes the "fix, commit, push, CI-fail"-cycle shorter.
Side note: CI now fails because the underlying `main` branch currently produces a warning that is fixed in #164.
=> Abort Sphinx build on warnings

docs/audit_report/changes/topics/chores.yml, docs/audit_report/changes/topics/fixes.yml
In Botan 3.3.0 most fixes have revolved round TLS so far. And here mostly the ASIO wrapper. Thank you, TLS Anvil.
=> Audit: Fixes

docs/audit_report/changes/topics/cli.yml
... let's have a deeper look into the MARVIN attack tools. Apparently most other libraries can be shown to be vulnerable: https://people.redhat.com/~hkario/marvin
=> Audit: Command Line Interface

.github/workflows/ci.yml, README.md, config/auditors.yml, docs/architecture/poetry.lock, docs/audit_method/poetry.lock, docs/audit_report/changes/topics/chores.yml, docs/audit_report/poetry.lock, docs/audit_report/src/00_09_introduction.rst, docs/audit_report/src/conf.py, docs/cryptodoc/poetry.lock, docs/testreport/poetry.lock, docs/testspec/poetry.lock, tools/auditinfo/auditinfo/__init__.py, tools/auditinfo/auditinfo/auditor.py, tools/auditinfo/auditinfo/botan.py, tools/auditinfo/poetry.lock, tools/auditinfo/pyproject.toml, tools/auditupdate/poetry.lock, tools/genaudit/genaudit/__init__.py, tools/genaudit/genaudit/cli.py, tools/genaudit/genaudit/topic.py, tools/genaudit/genaudit/verify.py, tools/genaudit/poetry.lock, tools/sourceref/poetry.lock
This adds an automated check to ensure that all referenced patches in the audit document are sufficiently denoted to assume that an audit was performed on it.
Note that I had to install `pyyaml` for `auditinfo`. Therefore, I needed to `poetry update` all downstream dependencies. Hence: sorry for the `poetry.lock` clutter in this PR.
Currently, this checks:
1. Is the patch authored, approved or audited by at least one authorative auditor, registered in config/auditors.yml
2. Is the patch classified regarding its relevance to the library's overall security
Note that we should not merge this until all currently registered patches are properly audited. Otherwise the `main` branch won't build anymore. As a side-effect this will also fail the Auto-Update pull request after the Bot created it. …
=> CI: Check Patch Audit Compliance

tools/genaudit/genaudit/cli.py
This lists all patches referenced in the audit document. A typical use case is to update the news.rst for Botan's release process.
Use like:
```bash
cd docs/audit_report
poetry run python3 -m genaudit.cli -r <path_to_botan_repo_checkout> list_patches changes --yaml
```
Typical output:
```
[...]
- pr: 3809  # https://github.com/randombit/botan/pull/3809
merge_commit: dc4ac416125ad294e17cbe925363ec14844341f4
classification: relevant
comment: |
Updates Botan's TLS policy to the latest recommendations of `TR-02102-2 <https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.html>`_.
In particular, enables support for TLS 1.3, adds secp521r1 and increases the required key lengths for RSA and DSA.
Also sets the minimum key strength to 120 and removes …
```
=> Add genaudit.cli list_patches

docs/cryptodoc/src/05_08_kyber.rst, tools/sourceref/sourceref/__init__.py, tools/sourceref/sourceref/role.py
This extends the `:srcref:` rST role with deep-links into specific source lines. This feature was explicitly requested [here](https://github.com/sehlen-bsi/botan-docs/pull/117#discussion_r1487454442). Additionally, I integrated the `:srcref:` extension @FAlbertDev added in #186.
As an example, I deep-linked a source location in the Kyber crypto doc. The result (in HTML output) looks like that:
... and links to: https://github.com/randombit/botan/blob/7f15ce7b39d6bd34dda9af4d2cb08a6e18c64c01/src/lib/pubkey/kyber/kyber_common/kyber.cpp#L1042
In reStructuredText the `:srcref:` annotation understands the following:
| Example | Description |
| --- | --- |
| ``:srcref:`src/lib/hash/sha1/sha1.cpp` `` | Simply link to the `sha1.cpp` on GitHub, using the full path as link text, namely …
=> Feature: `:srcref:` can deep-link to specific source lines

tools/auditupdate/auditupdate/cli.py
This became necessary, to support bootstraping after purging the directory when a new version ob Botan was just released upstream.
=> FIX: (re-)create topic file directory

.github/actions/setup-build-agent/action.yml, .github/workflows/auto-update.yml, .github/workflows/ci.yml, docs/architecture/poetry.lock, docs/audit_method/poetry.lock, docs/audit_report/poetry.lock, docs/cryptodoc/poetry.lock, docs/testreport/poetry.lock, docs/testspec/poetry.lock, tools/auditupdate/poetry.lock, tools/genaudit/poetry.lock
This updates some python dependencies and GitHub Actions.
Note in particular, that `actions/artifacts@v4` enforces immutable artifacts. I.e. we cannot upload to a single `junit` artifact from multiple jobs. Instead, artifacts must be job-unique. Fortunately, `actions/download-artifacts@v4` supports downloading and recombining based on a pattern. See [the official migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact).
Also, `actions/cache@v4` introduces `save-always`, so we can do away with our workaround of saving the API cache on failed jobs.
=> Chore: Update Things

docs/testspec/src/14_pubkey_sig.rst
Test specification for HSS/LMS tests. Note that the CI will currently fail since HSS/LMS is not yet merged into Botan.
=> HSS/LMS Testspecification

docs/cryptodoc/src/05_03_ecc.rst
Jack performed a refactoring (introducing new helper-structures) in ECC to prepare for [#3979](https://github.com/randombit/botan/pull/3979) to be used in 3.6.0 (see [#4027](https://github.com/randombit/botan/issues/4027)). The actual implementations (ECDH, ECDSA, ECGDSA, ECKCDSA) won't change much in 3.5.0, though. Fixes here are mostly details and inconsistencies I found on the way. Note that the commits bear more details about the actual changes.
=> Double-check crypto documentation of ECC

docs/architecture/pyproject.toml, docs/audit_method/pyproject.toml, docs/audit_report/pyproject.toml, docs/cryptodoc/pyproject.toml, docs/testreport/pyproject.toml, docs/testspec/pyproject.toml
I recently switched to Ubuntu 24.04 where poetry starting throwing around warnings about that.
Note that this requires the CI jobs to run on Ubuntu 24.04.
=> Chore: Use poetry for dependency mgmt only

.github/workflows/auto-update.yml
=> FIX: auto-update bot has to run on Ubuntu 24.04

docs/cryptodoc/src/00_01_changelog.rst, docs/cryptodoc/src/10_kdf.rst, docs/cryptodoc/src/90_bibliographie.rst, docs/testspec/src/06_kdf.rst
As mentioned in #221, I updated the Cryptodoc for the changes in https://github.com/randombit/botan/pull/4121.
=> Reflect Botan's NIST SP800-56r2 Changes

tools/genaudit/genaudit/topic.py
This fixes an issue where the audit generator would fail when a topic file contained an empty patch list, as:
```
title: Example
description: |
Irrelevant description...
patches:
```
=> FIX: audit patch list may be empty

config/botan.env, docs/architecture/src/01_architecture.rst, docs/architecture/src/conf.py, docs/audit_method/src/90_references.rst, docs/audit_method/src/conf.py, docs/audit_report/src/06_bibliography.rst, docs/audit_report/src/conf.py, docs/cryptodoc/src/90_bibliographie.rst, docs/cryptodoc/src/conf.py, docs/testreport/src/conf.py, docs/testspec/src/conf.py, internal/release_checklist.md, tools/auditinfo/auditinfo/botan.py
Update references to BSI TRs and internal document cross-references. Fix the section-specific references into the handbook. I added this to the release checklist, as it is a maintenance burden that we'll keep forgetting.
Also update (and centralize) the copyright information contained in each document.
=> Chore: Document Housekeeping

tools/auditinfo/auditinfo/auditor.py, tools/auditupdate/auditupdate/cli.py, tools/genaudit/genaudit/refs.py
This is how it looks:
```yaml
- pr: 4170  # https://github.com/randombit/botan/pull/4170
merge_commit: bb9c069a2688065bf354356190156a34cbce98d2
classification: unspecified
```
Now we can immediately see that a pull request was approved by some other user prior to merging upstream. Users that are defined as "authorative auditors" in this repository (see `config/auditors.yml`) will be rendered first. All other users will be in parenthesis.
I've been wishing to have this information handy for quite some time while categorizing patches after the auto-update bot had detected them on upstream.
=> Render list of Approvers into Patches from Auto-Update 

docs/architecture/pyproject.toml, docs/audit_method/pyproject.toml, docs/audit_report/pyproject.toml, docs/cryptodoc/pyproject.toml, docs/testreport/pyproject.toml, docs/testspec/pyproject.toml, tools/auditinfo/pyproject.toml, tools/auditupdate/pyproject.toml, tools/auditutils/pyproject.toml, tools/genaudit/pyproject.toml, tools/sourceref/pyproject.toml, tools/tarball_checker/pyproject.toml
When running poetry install with my default apt install poetry version on my Ubuntu 22.04 I get the (somehow cryptic) error:
```
The Poetry configuration is invalid:
- Additional properties are not allowed ('package-mode' was unexpected)
```
This is due to the small poetry version. Hopefully, this PR improves this error message for others.
=> Enforce Poetry Version >=1.8.0

docs/audit_report/changes/topics/crystals.yml, docs/audit_report/changes/topics/ct_helpers.yml, docs/audit_report/changes/topics/encoding.yml, docs/audit_report/changes/topics/fixes.yml
This PR covers the Botan 3.6.0 audit for crystals and CT Helpers
Progress: #242
=> 3.6.0 Audit: Crystals, CT Helpers, Encoding, Fixes

docs/testspec/src/12_pubkey_kem.rst, docs/testspec/src/14_pubkey_sig.rst
This PR contains the testspec adaptions for the three new FIPS 20X algorithms. I kept the level of detail roughly the same.
=> Testspec Update: ML-KEM, ML-DSA and SLH-DSA

.github/workflows/ci.yml, docs/audit_report/src/conf.py
Note that in contrast to the other documents, the URL check is incorporated into the normal document generation job on CI. The cache handling of the audit report job is just too complicated to refactor now.
I need those for the SCA PRs (#236 #237 #238) because these reports are referencing into the upstream code.
=> Enable :srcref: in audit report document

.github/actions/setup-build-agent/setup_gh_actions.sh
Some build machine setups had diverged from upstream. Mostly due to updates in GitHub Action's runner images. We should probably look into how to resolve the copy-pasta that `ci.yml` and `setup_build_agent.sh` are at some point.
=> FIX: CI build issues

docs/cryptodoc/src/05_05_xmss.rst, docs/cryptodoc/src/05_06_hss_lms.rst
Mentioned in #235. For the PQC signature algorithms, we wrote _validation_ where we meant _verification_. This PR fixes this issue for HSS/LMS and XMSS. For SLH-DSA and ML-DSA, this is fixed in the respective open PRs.
=> Validation → Verification

docs/cryptodoc/src/05_03_ecc.rst
I checked out the current cryptodoc and noticed it doesn't dive into the details of internal elliptic curve operations. I didn't want to get too specific, so I left most of it as is. But for those who want to dig deeper into the internals, I included a source reference to the pcurves module. Hope this suffices.
=> Cryptodoc Update: pcurves

docs/cryptodoc/src/07_rng.rst, docs/cryptodoc/src/90_bibliographie.rst
See https://github.com/randombit/botan/pull/4325 @dirkz
Closes #247
=> Add jitter_rng module to crypto documentation

docs/audit_report/src/06_bibliography.rst, docs/audit_report/src/side_channels/01_00_results.rst, docs/audit_report/src/side_channels/01_02_ml_dsa.rst
~~draft, not yet ready for review~~
=> side_channels: Add ML DSA report

docs/testspec/src/12_pubkey_kem.rst
Test specification for [Botan's Classic McEliece implementation](https://github.com/randombit/botan/pull/3883). Note that the CI will fail until the PR is merged into Botan.
=> Classic McEliece Testspecification

docs/audit_report/src/side_channels/01_00_results.rst, docs/audit_report/src/side_channels/01_01_cmce.rst
=> Classic McEliece Side Channel Report

docs/audit_report/changes/topics/doc_release.yml, docs/audit_report/changes/topics/documentation.yml, docs/audit_report/changes/topics/pcurve.yml
Updates to Botan's 'official' documentation were quite significant, nothing relevant to the implementation of the crypto algorithms in those categories though, obviously.
=> Audit: Updates to the Documentation

docs/cryptodoc/src/05_03_ecc.rst, docs/cryptodoc/src/90_bibliographie.rst
This contains a thorough rework of the elliptic curve algorithm documentation after Botan 3.7.1 brought the new 'pcurves' implementation as the new default for ECC algorithms.
See also #268
=> Rework ECC documentation
